name: CI Scheduled Test Run

on:
  schedule:
    - cron: '30 3 * * *'   # 09:00 IST
    - cron: '30 6 * * *'   # 12:00 IST
    - cron: '30 9 * * *'   # 15:00 IST
    - cron: '30 12 * * *'  # 18:00 IST
    - cron: '30 15 * * *'  # 21:00 IST
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set current IST time
        id: set_time
        run: echo "time=$(TZ='Asia/Kolkata' date '+%Y-%m-%d %H:%M:%S IST')" >> $GITHUB_OUTPUT

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Build and Test
        run: mvn clean test -Dtest=runner.ciTestRunner -Drun.time="${{ steps.set_time.outputs.time }}"

      - name: Archive Spark Report
        uses: actions/upload-artifact@v4
        with:
          name: spark-report
          path: test-output/SparkReport/