name: CI Actions

on:
  schedule:
    - cron: '30 3 * * *'   # 09:00 AM IST
    - cron: '30 15 * * *'  # 09:00 PM IST
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 23
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'
       #Setup
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: '3.9.6'

      - name: Build and run tests
        run: mvn clean test -Dtest=runner.ciTestRunner

      - name: Upload spark.html report
        uses: actions/upload-artifact@v4
        with:
          name: spark-report
          path: test-output/SparkReport/Spark.html